model = "F5TTS_Base"
ref_audio = "U:\\zenvyrolabsinternship\\Assignment2\\Full-Stack\\temp\\trimmed_ref_gen.wav"
ref_text = "heloo"
speed = 1.0
nfe_step = 16
gen_text = "heloo"
output_dir = "U:\\zenvyrolabsinternship\\Assignment2\\Full-Stack"
output_file = "output_cloned.wav"

[voices]
